import React, { useState, useEffect } from 'react'
import Head from 'next/head'
import Nav from '../Components/Nav'
import DefaultLayout from '../Layouts/DefaultLayout'
import Input from './Input'
import axios from 'axios'
import Zoom from 'react-medium-image-zoom'
import 'react-medium-image-zoom/dist/styles.css'


export default function Home() {

  const [students, setStudents] = useState([])

  useEffect( () => {
    axios.get('https://fejs-c7-api.herokuapp.com/api/students/?populate=*')
  .then( res => {
    setStudents([...res.data.data])
  })
  })

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <DefaultLayout>
        <h1 className='text-center'>Hii Welcome To Home</h1>
        {students.map((student) => {
          return(
            <div key={student.id} className="row">
              <div className="col">
                  <div  style={{width:'18rem'}}>
                  { student.attributes.photo.data !== null &&
                        <Zoom>
                          <img className="card-img-top"src={student.attributes.photo.data.attributes.url} style={{width:"200px", height:"auto"}}/>
                        </Zoom>
                      }
                      <div className="card-body">
                        <p className="card-text">First Name: {student.attributes.firstname}</p>
                        <p className="card-text">Last Name: {student.attributes.lastname}</p>
                        <p className="card-text">Location: {student.attributes.location}</p>
                      </div>
                </div>
              </div>
            </div>
          )
        })}
      </DefaultLayout>

     
    </div>
  )
}
